language: dart
sudo: false
dart:
- stable
with_content_shell: false
dart_task:
- dartanalyzer: --fatal-infos --fatal-warnings lib
- dartfmt
script:
  - set -e
  - pub run test test/giphy_client_test.dart
  - pub get --packages-dir
  - pub global activate coverage
  - dart --enable-vm-service=8111 --pause-isolates-on-exit test/giphy_client_test.dart &
  - pub global run coverage:collect_coverage --port=8111 --out=coverage.json --wait-paused --resume-isolates
  - pub global run coverage:format_coverage --lcov --in=coverage.json --out=lcov.info --packages=.packages --report-on=lib
after_success:
  - bash <(curl -s https://codecov.io/bash)
