name: flutter_emoji_gif_picker
description: The same emoji-gif picker as whatsapp. Takes the same size as your keyboard(Mobile).
version: 0.1.5
homepage: https://github.com/FlutterWay/flutter_emoji_gif_picker

environment:
  sdk: '>=2.18.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.1
  meta: ^1.11.0
  platform_info: ^4.0.2
  emoji_picker_flutter: 1.6.4
  flutter_keyboard_size: ^1.0.1
  
dev_dependencies:
  test: ^1.25.2
  mockito: ^5.4.4
  coverage: ^1.7.2
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0

flutter: